using System.Linq;
using Content.Client.Chat.Managers;
using Content.Client.Message;
using Content.Shared.Chat;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Silicons.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class LawDisplay : Control
{
    [Dependency] private readonly IChatManager _chatManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private static readonly TimeSpan PressCooldown = TimeSpan.FromSeconds(3);

    /// <summary>
    /// Explicit Order of this law, as understood by the Game Rules.
    /// This information is provided for additional clarity in order to make relative importance of laws explicitly clear,
    /// especially when corruption and/or other shenanigans are involved that make complicate reading it.
    /// </summary>
    public int LawOrder { get; private init; }

    /// <summary>
    /// How this law is identified in-character (i.e. "Law 1").
    /// This is usually correlated with Order of the laws (their relative importance), but not always.
    /// For roleplay-reasons they are not necessarily unique.
    /// </summary>
    public string LawIdentifier { get; private init; }
    public SiliconLaw Law { get; private init; }
    private readonly Dictionary<ChatChannelDescriptor, TimeSpan> _stateLawOnCooldownUntil = [];

    public LawDisplay(int order, string identifier, SiliconLaw law, List<ChatChannelDescriptor> chatChannels)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LawOrder = order;
        LawIdentifier = Loc.GetString("laws-ui-law-header", ("id", identifier));
        Law = law;

        var lawBodyString = FormattedLawString();
        LawNumberLabel.SetMarkup(LawIdentifier);
        LawLabel.SetMarkup(lawBodyString);

        UpdateStateLawButtons(chatChannels);
    }

    public void UpdateStateLawButtons(List<ChatChannelDescriptor> chatChannels, bool forceRedraw = false)
    {
        if (forceRedraw)
            RedrawStateLawButtons(chatChannels);
        else
            PatchStateLawButtons(chatChannels);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_stateLawOnCooldownUntil.Count == 0)
            return;

        var curTime = _timing.CurTime;

        // iterate over copy of keys because we are modifying the working set
        var toCheck = _stateLawOnCooldownUntil.Keys.ToArray();
        foreach (var chatChannel in toCheck)
        {
            if (_stateLawOnCooldownUntil[chatChannel] > curTime)
                continue;

            _stateLawOnCooldownUntil.Remove(chatChannel);
            EnableStateLawButton(chatChannel.Caption);
        }
    }

    /// <summary>
    /// Helper method to find and enable the button by its caption.
    /// </summary>
    private void EnableStateLawButton(string buttonText)
    {
        foreach (var control in LawAnnouncementButtons.Children)
        {
            if (control is not Button button)
                continue;

            if (button.Text == buttonText)
            {
                button.Disabled = false;
                break;
            }
        }
    }

    private void OnStateLawsButtonPressed(BaseButton sender, string message, string channelPrefix, ChatChannelDescriptor chatChannel)
    {
        if (_stateLawOnCooldownUntil.ContainsKey(chatChannel))
            return;

        // Send message in chat
        var chatSelectChannel = string.IsNullOrEmpty(channelPrefix) ? ChatSelectChannel.Local : ChatSelectChannel.Radio;
        _chatManager.SendMessage($"{channelPrefix} {message}", chatSelectChannel);

        // Set cooldown if any
        if (PressCooldown <= TimeSpan.Zero)
            return;

        _stateLawOnCooldownUntil[chatChannel] = _timing.CurTime + PressCooldown;
        sender.Disabled = true;
    }

    /// <summary>
    /// Base update UI variant. Clears old state law buttons and draws new.
    /// When in doubt - use this.
    /// </summary>
    private void RedrawStateLawButtons(List<ChatChannelDescriptor> chatChannels)
    {
        LawAnnouncementButtons.RemoveAllChildren();

        if (chatChannels.Count == 0)
            return;

        var lawBodyString = FormattedLawString();
        var stateLawMessage = $"{FormattedMessage.RemoveMarkupPermissive(LawIdentifier)}: {FormattedMessage.RemoveMarkupPermissive(lawBodyString)}";

        foreach (var chatChannel in chatChannels)
            AddNewStateLawButton(stateLawMessage, chatChannel);
    }

    /// <summary>
    /// Optimized update UI variant.
    /// Calculates a net delta change and only redraws what needs to be redrawn.
    /// </summary>
    private void PatchStateLawButtons(List<ChatChannelDescriptor> chatChannels)
    {
        var channelsToSeekMatchFor = new List<ChatChannelDescriptor>(chatChannels);
        var validStateLawButtons = new Dictionary<ChatChannelDescriptor, Button>(LawAnnouncementButtons.ChildCount);
        var nonReusableControls = new List<Control>(LawAnnouncementButtons.ChildCount);
        foreach (var lawAnnouncementButtonsChild in LawAnnouncementButtons.Children)
        {
            if (lawAnnouncementButtonsChild is not Button stateLawButton)
            {
                // Not a Button at all (what's it doing here?)
                nonReusableControls.Add(lawAnnouncementButtonsChild);
                continue;
            }

            var foundMatch = false;
            foreach (var channel in channelsToSeekMatchFor)
                if (channel.Caption == stateLawButton.Text)
                {
                    // The StateLawButton we are looking for
                    validStateLawButtons.Add(channel, stateLawButton);
                    channelsToSeekMatchFor.Remove(channel); // Stop searching among ones that we already found a match for.
                    foundMatch = true;
                    break;
                }

            if (foundMatch)
                continue;

            // Not the StateLawButton we are looking for
            nonReusableControls.Add(lawAnnouncementButtonsChild);
        }

        foreach (var nonReusableControl in nonReusableControls)
            LawAnnouncementButtons.RemoveChild(nonReusableControl);

        if (chatChannels.Count == 0)
            return;

        var lawBodyString = FormattedLawString();
        var stateLawMessage = $"{FormattedMessage.RemoveMarkupPermissive(LawIdentifier)}: {FormattedMessage.RemoveMarkupPermissive(lawBodyString)}";

        for (var i = 0; i < chatChannels.Count; i++)
        {
            var chatChannel = chatChannels[i];

            if (validStateLawButtons.TryGetValue(chatChannel, out var thisStateLawButton))
                thisStateLawButton.SetPositionInParent(i);
            else
            {
                var button = AddNewStateLawButton(stateLawMessage, chatChannel);
                button.SetPositionInParent(i);
            }
        }
    }

    private Button AddNewStateLawButton(string stateLawMessage, ChatChannelDescriptor chatChannel)
    {
        var button = new Button
        {
            Text = chatChannel.Caption,
            Modulate = chatChannel.Color,
            StyleClasses = { "chatSelectorOptionButton" },
            MinHeight = 35,
            MinWidth = 75,
            Disabled = _stateLawOnCooldownUntil.ContainsKey(chatChannel)
        };

        button.OnPressed += e => OnStateLawsButtonPressed(e.Button, stateLawMessage, chatChannel.ChannelPrefix, chatChannel);
        LawAnnouncementButtons.AddChild(button);
        return button;
    }

    private string FormattedLawString()
    {
        var raw = Loc.GetString(Law.LawString);

        if (!_proto.TryIndex(Law.LawFormat, out var lawFormat))
            return raw;

        return lawFormat.ApplyFormat(raw);
    }
}
